# =========================================
# Server Configuration
# =========================================
server:
  port: 8090 # <<<--- Porta para o cash-flow-service (exemplo)

# =========================================
# Spring Boot Application Configuration
# =========================================
spring:
  application:
    name: cash-flow-service

  # =========================================
  # Datasource Configuration (PostgreSQL) - Only for Manual Entries
  # =========================================
  datasource:
    url: jdbc:postgresql://localhost:5432/cashflowdb # <<<-- BD Dedicado (Recomendado)
    username: postgres
    password: postgres

  # =========================================
  # JPA & Hibernate Configuration
  # =========================================
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

# =========================================
# External Service URLs
# =========================================
auth:
  service:
    url: ${AUTH_SERVICE_URL:http://localhost:8083/api} # <<<--- URL do Auth Service
payable:
  service:
    url: ${PAYABLE_SERVICE_URL:http://localhost:8088/api} # <<<--- URL do Payable Service (ajuste a porta 8088)
receivable:
  service:
    url: ${RECEIVABLE_SERVICE_URL:http://localhost:8089/api} # <<<--- URL do Receivable Service (ajuste a porta 8089)

# =========================================
# JWT Configuration
# =========================================
jwt:
  secret: ${JWT_SECRET_KEY:404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970!} # <<<--- MESMA CHAVE SECRETA

# =========================================
# Logging & Swagger (Similar aos outros)
# =========================================
logging:
  level:
    org.springframework.web: INFO
    org.springframework.security: INFO
    com.bufalari.cashflow: DEBUG # Seu pacote
    org.hibernate.SQL: DEBUG
    # Log Feign details
    # com.bufalari.cashflow.client: DEBUG

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: method
  default-consumes-media-type: application/json
  default-produces-media-type: application/json